#version of MySQL used = 5.7
#latest version of drupal is used

version: "3"
services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: carryminati
      MYSQL_USER: Anjali
      MYSQL_PASSWORD: carryminati
      MYSQL_DATABASE: mydatabase

  drupal:
    image: drupal:latest
    restart: always
    depends_on:
      - dbos
    ports:
      - 7070:80
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: Anjali
      POSTGRES_HOST: dbos
      POSTGRES_PASSWORD: carryminati
    volumes:
      - drupal_storage:/var/www/html
    
volumes:
  mysql_storage:
  drupal_storage:
